"""Domain models and persistence."""

from models.analysis_metadata import AnalysisMetadataStore, AnalysisRunRecord, persist_forecast_run
from models.domain_types import (
    ColumnProfile,
    DetectedSchema,
    ForecastExplanation,
    ForecastKpis,
    ForecastMetric,
    ForecastPoint,
    ForecastRunResult,
    MetricForecastBundle,
    ModelKind,
    ModelSelectionResult,
    MonthlySeries,
    ParsedEvent,
    SafeMetricSet,
    SameMonthHistoricalStats,
    SchemaMappingOverride,
    SegmentComparison,
    ValidationIssue,
    ValidationReport,
    ValidationStrategy,
    VolumeAggregationMode,
    event_has_adjustable_magnitude,
)

__all__ = [
    "AnalysisMetadataStore",
    "AnalysisRunRecord",
    "persist_forecast_run",
    "ColumnProfile",
    "DetectedSchema",
    "SchemaMappingOverride",
    "ForecastExplanation",
    "ForecastKpis",
    "ForecastMetric",
    "ForecastPoint",
    "ForecastRunResult",
    "MetricForecastBundle",
    "ModelKind",
    "ModelSelectionResult",
    "MonthlySeries",
    "ParsedEvent",
    "event_has_adjustable_magnitude",
    "SafeMetricSet",
    "SameMonthHistoricalStats",
    "SegmentComparison",
    "ValidationIssue",
    "ValidationReport",
    "ValidationStrategy",
    "VolumeAggregationMode",
]
